const products = [
  {
    id: 1,
    foodType: "Pizza",
    name: "Margherita",
    desc: "Classic cheese and tomato pizza",
    rating: "4.5",
    price: 12.99,
    img: "https://example.com/margherita.jpg",
    category: "Italian",
    amount: 1,
    isFav: true,
    isNew: false,
    isPopular: true,
  },
  {
    id: 2,
    foodType: "Burger",
    name: "Veggie Burger",
    desc: "Delicious vegetarian burger",
    rating: "4.2",
    price: 9.99,
    img: "https://example.com/veggieburger.jpg",
    category: "Fast Food",
    amount: 1,
    isFav: false,
    isNew: true,
    isPopular: false,
  },
  {
    id: 3,
    foodType: "Salad",
    name: "Caesar Salad",
    desc: "Fresh Caesar salad with croutons",
    rating: "4.7",
    price: 8.5,
    img: "https://example.com/caesarsalad.jpg",
    category: "Healthy",
    amount: 1,
    isFav: false,
    isNew: false,
    isPopular: true,
  },
];

// [
//   // === Category: Soups ===
//   {
//     id: 1,
//     name: "Egusi Soup",
//     desc: "Melon seed soup cooked with vegetables, palm oil, and assorted meat",
//     rating: "4.8",
//     price: 15.0,
//     img: "https://res.cloudinary.com/ddxbkmpcu/image/upload/v1756747080/kukin/z3az1msbxbnanzizync8.jpg",
//     category: "Soups",
//     amount: 1,
//     isFav: true,
//     isNew: false,
//     isPopular: true,
//   },
//   {
//     id: 2,
//     name: "Okra Soup",
//     desc: "Delicious slimy soup made with okra, palm oil, and assorted meat",
//     rating: "4.6",
//     price: 14.0,
//     img: "https://example.com/okra.jpg",
//     category: "Soups",
//     amount: 1,
//     isFav: false,
//     isNew: true,
//     isPopular: false,
//   },
//   {
//     id: 3,
//     name: "Afang Soup",
//     desc: "Calabar delicacy made with waterleaf, okazi leaves, and periwinkle",
//     rating: "4.7",
//     price: 16.0,
//     img: "https://example.com/afang.jpg",
//     category: "Soups",
//     amount: 1,
//     isFav: false,
//     isNew: false,
//     isPopular: true,
//   },
//   {
//     id: 4,
//     name: "Efo Riro",
//     desc: "Yoruba spinach stew made with assorted meats and spices",
//     rating: "4.9",
//     price: 15.5,
//     img: "https://example.com/eforiro.jpg",
//     category: "Soups",
//     amount: 1,
//     isFav: true,
//     isNew: false,
//     isPopular: true,
//   },

//   // === Category: Rice Dishes ===
//   {
//     id: 5,
//     name: "Jollof Rice",
//     desc: "Smoky party-style Jollof rice cooked with tomatoes and spices",
//     rating: "5.0",
//     price: 12.0,
//     img: "https://example.com/jollof.jpg",
//     category: "Rice Dishes",
//     amount: 1,
//     isFav: true,
//     isNew: false,
//     isPopular: true,
//   },
//   {
//     id: 6,
//     name: "Fried Rice",
//     desc: "Rice stir-fried with vegetables, liver, and spices",
//     rating: "4.6",
//     price: 12.5,
//     img: "https://example.com/friedrice.jpg",
//     category: "Rice Dishes",
//     amount: 1,
//     isFav: false,
//     isNew: true,
//     isPopular: false,
//   },
//   {
//     id: 7,
//     name: "Ofada Rice & Ayamase",
//     desc: "Local rice served with green pepper sauce and assorted meats",
//     rating: "4.8",
//     price: 18.0,
//     img: "https://example.com/ofada.jpg",
//     category: "Rice Dishes",
//     amount: 1,
//     isFav: true,
//     isNew: false,
//     isPopular: true,
//   },
//   {
//     id: 8,
//     name: "Coconut Rice",
//     desc: "Rice cooked in rich coconut milk with spices and vegetables",
//     rating: "4.4",
//     price: 13.0,
//     img: "https://example.com/coconutrice.jpg",
//     category: "Rice Dishes",
//     amount: 1,
//     isFav: false,
//     isNew: true,
//     isPopular: false,
//   },

//   // === Category: Grilled & Meat Dishes ===
//   {
//     id: 9,
//     name: "Suya",
//     desc: "Spicy grilled beef skewers served with onions and pepper mix",
//     rating: "4.9",
//     price: 10.0,
//     img: "https://example.com/suya.jpg",
//     category: "Grilled & Meat",
//     amount: 1,
//     isFav: true,
//     isNew: false,
//     isPopular: true,
//   },
//   {
//     id: 10,
//     name: "Asun",
//     desc: "Spicy smoked goat meat chunks stir-fried with pepper",
//     rating: "4.7",
//     price: 14.0,
//     img: "https://example.com/asun.jpg",
//     category: "Grilled & Meat",
//     amount: 1,
//     isFav: false,
//     isNew: true,
//     isPopular: true,
//   },
//   {
//     id: 11,
//     name: "Nkwobi",
//     desc: "Cow leg in rich palm oil and pepper sauce",
//     rating: "4.6",
//     price: 13.5,
//     img: "https://example.com/nkwobi.jpg",
//     category: "Grilled & Meat",
//     amount: 1,
//     isFav: false,
//     isNew: false,
//     isPopular: false,
//   },
//   {
//     id: 12,
//     name: "Kilishi",
//     desc: "Spicy dried beef jerky snack, northern Nigerian style",
//     rating: "4.5",
//     price: 9.0,
//     img: "https://example.com/kilishi.jpg",
//     category: "Grilled & Meat",
//     amount: 1,
//     isFav: false,
//     isNew: false,
//     isPopular: true,
//   },

//   // === Category: Swallows & Staples ===
//   {
//     id: 13,
//     name: "Pounded Yam & Egusi",
//     desc: "Smooth pounded yam served with rich egusi soup",
//     rating: "5.0",
//     price: 18.0,
//     img: "https://example.com/poundedyam.jpg",
//     category: "Swallows",
//     amount: 1,
//     isFav: true,
//     isNew: false,
//     isPopular: true,
//   },
//   {
//     id: 14,
//     name: "Amala & Ewedu",
//     desc: "Yam flour swallow served with ewedu and gbegiri soup",
//     rating: "4.7",
//     price: 16.0,
//     img: "https://example.com/amala.jpg",
//     category: "Swallows",
//     amount: 1,
//     isFav: false,
//     isNew: true,
//     isPopular: false,
//   },
//   {
//     id: 15,
//     name: "Fufu & Ogbono",
//     desc: "Cassava fufu paired with thick ogbono soup",
//     rating: "4.8",
//     price: 15.0,
//     img: "https://example.com/fufu.jpg",
//     category: "Swallows",
//     amount: 1,
//     isFav: false,
//     isNew: false,
//     isPopular: true,
//   },
//   {
//     id: 16,
//     name: "Tuwo Shinkafa & Miyan Kuka",
//     desc: "Rice swallow served with baobab leaf soup, northern Nigerian style",
//     rating: "4.6",
//     price: 14.5,
//     img: "https://example.com/tuwo.jpg",
//     category: "Swallows",
//     amount: 1,
//     isFav: true,
//     isNew: false,
//     isPopular: false,
//   },

//   // === Category: Snacks & Street Food ===
//   {
//     id: 17,
//     name: "Akara",
//     desc: "Crispy bean cakes fried in palm oil or vegetable oil",
//     rating: "4.5",
//     price: 5.0,
//     img: "https://example.com/akara.jpg",
//     category: "Snacks",
//     amount: 1,
//     isFav: false,
//     isNew: true,
//     isPopular: true,
//   },
//   {
//     id: 18,
//     name: "Puff-Puff",
//     desc: "Sweet deep-fried dough balls, soft and fluffy",
//     rating: "4.7",
//     price: 4.5,
//     img: "https://example.com/puffpuff.jpg",
//     category: "Snacks",
//     amount: 1,
//     isFav: true,
//     isNew: false,
//     isPopular: true,
//   },
//   {
//     id: 19,
//     name: "Boli",
//     desc: "Grilled plantain served with groundnut or pepper sauce",
//     rating: "4.8",
//     price: 6.0,
//     img: "https://example.com/boli.jpg",
//     category: "Snacks",
//     amount: 1,
//     isFav: true,
//     isNew: false,
//     isPopular: true,
//   },
//   {
//     id: 20,
//     name: "Moi Moi",
//     desc: "Steamed bean pudding with fish, egg, or corned beef",
//     rating: "4.6",
//     price: 7.5,
//     img: "https://example.com/moimoi.jpg",
//     category: "Snacks",
//     amount: 1,
//     isFav: false,
//     isNew: true,
//     isPopular: false,
//   },
// ];


module.exports = products;